name: Build and release a package
on:
    push:
        branches:
            - release

jobs:
    release:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '15'

            - name: Install dependencies
              run: npm install

            - name: Copy .env from secrets
              run: "echo ${WOLNABIBLIOTEKA_ENV_FILE} > .env"
              env:
                  WOLNABIBLIOTEKA_ENV_FILE: "${{ secrets.WOLNABIBLIOTEKA_ENV_FILE }}"

            - name: Build production version
              run: npm run build

            - name: Release to FTP server
              uses: SamKirkland/FTP-Deploy-Action@4.0.0
              with:
                  server: ${{ secrets.WOLNABIBLIOTEKA_FTP_SERVER }}
                  username: ${{ secrets.WOLNABIBLIOTEKA_FTP_USERNAME }}
                  password: ${{ secrets.WOLNABIBLIOTEKA_FTP_PASSWORD }}
                  local-dir: "./build/"
                  server-dir: "/"
                  dry-run: "false"
